version: '3.9'

# env_file:
#   - path: ./.env

services:
  frontend:
    image: xedom/codeduel-fe
    container_name: frontend
    restart: unless-stopped
    profiles: ['all', 'frontend']
    ports: ['5173:80']
    # depends_on: ['backend']
    environment:
      - TZ=Europe/Rome
    networks: ['traefik_proxy', 'codeduel']
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.codeduel.entrypoints=web,websecure'
      - 'traefik.http.routers.codeduel.rule=Host(`codeduel.it`)'
      - 'traefik.http.services.codeduel.loadbalancer.server.port=80'
      - 'traefik.http.routers.codeduel.tls=true'
      - 'traefik.http.routers.codeduel-be.tls.certresolver=myresolver'

  database:
    image: mariadb
    container_name: database
    restart: unless-stopped
    profiles: ['all', 'database']
    # ports: ['3306:3306']
    networks: ['codeduel']
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}

  backend:
    image: xedom/codeduel-backend
    container_name: backend
    restart: unless-stopped
    profiles: ['all', 'api', 'backend']
    ports: ['5000:80']
    # volumes:
    #  - /home/xe/docker/codeduel/ssl:/ssl
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}

      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
      AUTH_GITHUB_CLIENT_CALLBACK_URL: ${AUTH_GITHUB_CLIENT_CALLBACK_URL}

      FRONTEND_URL: ${FRONTEND_URL}
      LOGIN_REDIRECT: ${LOGIN_REDIRECT}

      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      COOKIE_PATH: ${COOKIE_PATH}
      COOKIE_HTTP_ONLY: ${COOKIE_HTTP_ONLY}
      COOKIE_SECURE: ${COOKIE_SECURE}

      CORS_ORIGIN: ${CORS_ORIGIN}
      CORS_METHODS: ${CORS_METHODS}
      CORS_HEADERS: ${CORS_HEADERS}
      CORS_CREDENTIALS: ${CORS_CREDENTIALS}

      ACCESS_TOKEN_COOKIE_NAME: ${ACCESS_TOKEN_COOKIE_NAME}
      ACCESS_TOKEN_EXPIRES: ${ACCESS_TOKEN_EXPIRES}
      REFRESH_TOKEN_COOKIE_NAME: ${REFRESH_TOKEN_COOKIE_NAME}
      REFRESH_TOKEN_EXPIRES: ${REFRESH_TOKEN_EXPIRES}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      
      SERVICE_HEADER_NAME: ${SERVICE_HEADER_NAME}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
    # depends_on: ['database']
    networks: ['traefik_proxy', 'codeduel']
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.codeduel-be.entrypoints=web,websecure'
      - 'traefik.http.routers.codeduel-be.rule=Host(`api.codeduel.it`)'
      - 'traefik.http.services.codeduel-be.loadbalancer.server.port=80'
      - 'traefik.http.routers.codeduel-be.tls=true'
      - 'traefik.http.routers.codeduel-be.tls.certresolver=myresolver'
        #- 'traefik.http.routers.codeduel-be.middlewares=redirect@file'
        #- 'traefik.http.routers.codeduel-be.middlewares=no-redirect@file'

  lobby:
    image: xedom/codeduel-lobby
    container_name: lobby
    restart: unless-stopped
    profiles: ['all', 'api', 'lobby']
    ports: ['5010:80']
    environment:
      BACKEND_URL: ${BACKEND_URL}
      BACKEND_API_KEY: ${BACKEND_API_KEY}

      RUNNER_URL: ${RUNNER_URL}
      RUNNER_API_KEY: ${RUNNER_API_KEY}
    # depends_on: ['runner']
    networks: ['codeduel', 'traefik_proxy']
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.codeduel-lobby.entrypoints=web,websecure'
      - 'traefik.http.routers.codeduel-lobby.rule=Host(`lobby.codeduel.it`)'
      - 'traefik.http.services.codeduel-lobby.loadbalancer.server.port=80'
      - 'traefik.http.routers.codeduel-lobby.tls=true'
      - 'traefik.http.routers.codeduel-lobby.tls.certresolver=myresolver'

  runner:
    image: xedom/codeduel-runner
    container_name: runner
    restart: unless-stopped
    profiles: ['all', 'api', 'runner']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports: [ '5020:5020' ]
    networks: ['codeduel']
    environment:
      FRONTEND_URL: '*'

networks:
  traefik_proxy:
    # name: traefik_proxy
    # external: true
  codeduel:
