version: '3.9'

services:
  frontend:
    networks: ['traefik_proxy']
    ports: !reset []
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.codeduel.entrypoints=web,websecure'
      - 'traefik.http.routers.codeduel.rule=Host(`codeduel.it`)'
      - 'traefik.http.services.codeduel.loadbalancer.server.port=80'
      - 'traefik.http.routers.codeduel.tls=true'
      - 'traefik.http.routers.codeduel-be.tls.certresolver=myresolver'

  backend:
    networks: ['traefik_proxy']
    ports: !reset []
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.codeduel-be.entrypoints=web,websecure'
      - 'traefik.http.routers.codeduel-be.rule=Host(`api.codeduel.it`)'
      - 'traefik.http.services.codeduel-be.loadbalancer.server.port=80'
      - 'traefik.http.routers.codeduel-be.tls=true'
      - 'traefik.http.routers.codeduel-be.tls.certresolver=myresolver'
      # - 'traefik.http.routers.codeduel-be.middlewares=redirect@file'
      # - 'traefik.http.routers.codeduel-be.middlewares=no-redirect@file'

  lobby:
    networks: ['traefik_proxy']
    ports: !reset []
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.codeduel-lobby.entrypoints=web,websecure'
      - 'traefik.http.routers.codeduel-lobby.rule=Host(`lobby.codeduel.it`)'
      - 'traefik.http.services.codeduel-lobby.loadbalancer.server.port=80'
      - 'traefik.http.routers.codeduel-lobby.tls=true'
      - 'traefik.http.routers.codeduel-lobby.tls.certresolver=myresolver'

networks:
  traefik_proxy:
