version: '3.8'

# env_file:
#   - path: ./.env

services:
  frontend:
    image: xedom/codeduel-fe
    container_name: frontend
    restart: always
    # profiles: ["fe"]
    # ports: ["5173:80"]
    # depends_on: ["backend"]
    networks: ["traefik_proxy"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codeduel.entrypoints=web,websecure"
      - "traefik.http.routers.codeduel.rule=Host(`codeduel.it`)"
      - "traefik.http.services.codeduel.loadbalancer.server.port=80"
      - "traefik.http.routers.codeduel.tls=true"
      - "traefik.http.routers.codeduel.tls.certresolver=myresolver"
      - "traefik.http.routers.codeduel-be.middlewares=redirect@file"

  database:
    image: mariadb
    container_name: database
    restart: always
    profiles: ["db"]
    # ports: ["3306:3306"]
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}

  backend:
    image: xedom/codeduel-be
    container_name: backend
    restart: always
    #ports: ["5000:5000"]
    environment:
      HOST: ${HOST_BACKEND}
      PORT: ${PORT_BACKEND}

      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_USER: ${MARIADB_USER}

      AUTH_GITHUB_CLIENT_CALLBACK_URL: ${AUTH_GITHUB_CLIENT_CALLBACK_URL}
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}

      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      COOKIE_PATH: ${COOKIE_PATH}
      COOKIE_HTTP_ONLY: ${COOKIE_HTTP_ONLY}
      COOKIE_SECURE: ${COOKIE_SECURE}

      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_URL_AUTH_CALLBACK: ${FRONTEND_URL_AUTH_CALLBACK}

      JWT_SECRET: ${JWT_SECRET}
    # depends_on: ["database"]
    expose: [80]
    networks: ["traefik_proxy"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codeduel-be.entrypoints=web"
      - "traefik.http.routers.codeduel-be.rule=Host(`api.codeduel.it`)"
      - "traefik.http.services.codeduel-be.loadbalancer.server.port=80"
      # - "traefik.http.routers.codeduel-be.middlewares=no-redirect@file"

  lobby:
    image: xedom/codeduel-lobby
    container_name: lobby
    restart: always
    ports:
      - 5010:5010
    environment:
      HOST: ${HOST_LOBBY}
      PORT: ${PORT_LOBBY}
      BINARY_NAME: codeduel-lobby

      BACKEND_URL: ${BACKEND_URL}
      BACKEND_API_KEY: ${BACKEND_API_KEY}

      RUNNER_URL: ${RUNNER_URL}
      RUNNER_API_KEY: ${RUNNER_API_KEY}
    # depends_on: ["runner"]

  runner:
    image: xedom/codeduel-runner
    container_name: runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports: [ "5020:5020" ]
    environment:
      HOST_: ${HOST_RUNNER}
      PORT: ${PORT_RUNNER}
      BINARY_NAME: codeduel-runner
      FRONTEND_URL: '*'
      DOCKER_IMAGE_PREFIX: cd-runner-
      DOCKER_TIMEOUT: 5s

networks:
  traefik_proxy:
    driver: overlay
    name: traefik_proxy
