version: '3.8'

env_file:
  - path: ./.env

services:
  database:
    image: mariadb
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}

  backend:
    image: xedom/codeduel-be
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    environment:
      HOST: ${HOST_BACKEND}
      PORT: ${PORT_BACKEND}

      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_USER: ${MARIADB_USER}

      AUTH_GITHUB_CLIENT_CALLBACK_URL: ${AUTH_GITHUB_CLIENT_CALLBACK_URL}
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}

      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_URL_AUTH_CALLBACK: ${FRONTEND_URL_AUTH_CALLBACK}
    depends_on:
      - database

  lobby:
    image: xedom/codeduel-lobby
    container_name: lobby
    restart: always
    ports:
      - 5010:5010
    environment:
      HOST: ${HOST_LOBBY}
      PORT: ${PORT_LOBBY}
      BINARY_NAME: codeduel-lobby

      BACKEND_URL: ${BACKEND_URL}
      BACKEND_API_KEY: ${BACKEND_API_KEY}

      RUNNER_URL: ${RUNNER_URL}
      RUNNER_API_KEY: ${RUNNER_API_KEY}
    depends_on:
      - runner

  runner:
    image: xedom/codeduel-runner
    container_name: runner
    restart: always
    ports:
      - 5020:5020
    environment:
      HOST_: ${HOST_RUNNER}
      PORT: ${PORT_RUNNER}
      BINARY_NAME: codeduel-runner
      FRONTEND_URL: '*'
      DOCKER_IMAGE_PREFIX: cd-runner-
      DOCKER_TIMEOUT: 5s
